### ISSUE TITLE
Failing to correctly resolve a `git diff`

### ISSUE THREAD

**Issue by Iron-Ham** [lerebear/sizeup-action#23]
## Summary

After updating to v0.4.0, I find that my sizeup action fails early as it is unable to evaluate a diff between the branch it is running on vs. the merge-base. 

My `config.yaml` is as follows:

```yaml
optIns:
  - [REDACTED]
  - [REDACTED]
labeling:
  applyCategoryLabels: true
  categoryLabelPrefix: "size/"
commenting:
  addCommentWhenScoreThresholdHasBeenExceeded: true
  scoreThreshold: 100
  commentTemplate: |
    👋 @{{author}} this pull request exceeds the recommended reviewability score threshold of {{threshold}}. Your actual score was {{score}}.

    [Research](https://www.cabird.com/static/93aba3256c80506d3948983db34d3ba3/rigby2013convergent.pdf) has shown that this makes it harder for reviewers to provide quality feedback.

    We recommend that you reduce the size of this PR by separating commits into stacked PRs.

    For more information and to provide feedback, please see [this discussion][LINK_REDACTED].
sizeup:
  categories:
    - name: extra small
      lte: 10
      label:
        name: XS
        description: Should be very easy to review
        color: 3cbf00
    - name: small
      lte: 30
      label:
        name: S
        description: Should be easy to review
        color: 5d9801
    - name: medium
      lte: 100
      label:
        name: M
        description: Should be of average difficulty to review
        color: 7f7203
    - name: large
      lte: 300
      label:
        name: L
        description: May be hard to review
        color: a14c05
    - name: extra large
      lte: 1000
      label:
        name: XL
        description: May be very hard to review
        color: c32607
    - name: extra extra large
      label:
        name: XXL
        description: May be extremely hard to review
        color: e50009
  ignoredFilePatterns:
    - CODEOWNERS
    - SERVICEOWNERS
    - Modules/Emoji/Resources/EmojiData.swift
    - Modules/REDACTED/Sources/Generated/**/*
    - Modules/REDACTED/Sources/Generated/**/*
    - Modules/GraphQL/Sources/**/*
    - Modules/GraphQL/VersionedDocuments/**/*
    - Modules/GraphQLExtension/Sources/**/*
    - Packages/TreeSitterLanguages/Sources/**/*
    - SettingsPresets/**/*
    - Modules/**/*.strings
    - Modules/**/*.stringsdict
  testFilePatterns:
    - "*Tests.swift"
    - "*Test.swift"
  scoring:
    formula: "- - - - + additions deletions comments whitespace * 0.5 single-words * 0.5 tests"
```

## Steps to reproduce

1. Open a pull request of any size that relies on v.0.4.0.

## Expected Behavior

We are able to evaluate the diff

## Actual Behavior

We are unable to evaluate the diff.

<img width="761" alt="Screenshot 2023-11-27 at 11 52 35 AM" src="https://github.com/lerebear/sizeup-action/assets/3388381/df86d99e-3e1c-47bb-a029-a21a86c8aebf">

Notably, when I locally run the code the action attempts to (and fails) to run, I do get a valid diff:

<img width="727" alt="Screenshot 2023-11-27 at 11 56 49 AM" src="https://github.com/lerebear/sizeup-action/assets/3388381/1f25c6e0-0c6f-4053-b41c-a4521abc9e1e">

**Comment by lerebear** [comment]
@Iron-Ham, sorry that this was unclear, but`0.4.0` now requires an extra bit of configuration in your workflow file:

```yaml
    steps:
      # You must add the new step below.
      - name: 'Set checkout depth to include base commit'
        id: 'set-checkout-depth'
        run: echo "depth=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "$GITHUB_OUTPUT"

      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          # You must add this argument.
          fetch-depth: "${{ steps.set-checkout-depth.outputs.depth }}"
```

So that's two things:

1. An extra workflow step that sets the total number of commits to check out.
2. An extra argument to the checkout step that makes sure we in fact check out the correct number of commits.

Both of those things make it so that we can resolve the diff with custom `git diff` args, which allows us to do things like [ignore whitespace changes by default](https://github.com/lerebear/sizeup-action/issues/20).
