### ISSUE TITLE
Feature Request: Ignored Branches

### ISSUE THREAD

**Issue by Iron-Ham** [lerebear/sizeup-action#29]
I find myself on occasion making hot-fixes to release branches. Hotfixes are composed of merged and reviewed individual PRs that are being cherry-picked.

When pointing a hotfix pull request at a release branch, I'd love if I could not have size-up let me know that this is too big for one PR, as it's often composed of many smaller, independently reviewed chunks. Concretely: I'd like to have an `ignoredBranches` argument that i can supply a branch name or pattern.

Something like:

```yaml
ignoredBranches:
  - releases/*
  - staff_releases/*
  - etc
```

**Comment by lerebear** [comment]
Yes, I see how such support could be really useful. There are actually a few options for this that are built into the Actions framework itself. @Iron-Ham might either of the two options below serve you?

1. Use the  [`branches` configuration option for the `pull_request` event target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request), to define an allowlist for the base branch that the pull request targets:

```yaml
# In .github/workflows/sizeup.yaml

name: SizeUp

on: pull_request
  branches: # ❗ Only run the sizeup workflow on the branches listed below
    - main
    - 'topic*'
```

2. Use the [`github.base_ref` context variable](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to write a [condition](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) that restricts the workflow to certain branches:

```yaml
# In .github/workflows/sizeup.yaml

name: SizeUp

...

jobs:
  sizeup:
    if: ${{ ! startsWith(github.base_ref, 'release') }} # ❗ Do not run the sizeup workflow on release branches
```
