### ISSUE TITLE
Use a more intuitive name for the `archiving` config options

### ISSUE THREAD

**Issue by lerebear** [lerebear/sizeup-action#48]
As pointed out by a user of this action, "archiving" is not an intuitive name for the configuration options that control how this action creates artifacts. We should consider renaming those configuration options.

The suggestion made by the user was that we move to a configuration that looks like this:

```yaml
artifacts:
  persistScore: true
  retention: 30
```
