### ISSUE TITLE
Error "Destination path is not an empty directory" when specifying a configuration file

### ISSUE THREAD

**Issue by ppsmilesi** [lerebear/sizeup-action#55]
Hello !

Thank you for the github action and the sizeup library, it looks awesome !

I have tried to run the action with a configuration file without success.
I have checked out the config file at first step of the workflow for it to be available but then, the sizeup action has run into this error:
`Error: fatal: destination path '.' already exists and is not an empty directory.`

Output of the workflow:
```
Run lerebear/sizeup-action@v0.8.3
  with:
    token: ***
    configuration-file-path: .github/workflows/sizeup/config.yml
    git-diff-options: --ignore-space-change
Reading sizeup configuration from ".github/workflows/sizeup/config.yml"
Evaluating pull request ...
Error: fatal: destination path '.' already exists and is not an empty directory.
```

Workflow fiile `.github/workflows/sizeup.yml`:
```
name: SizeUp

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Estimate reviewability
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Check out the repository to be able to read config file
        with:
          sparse-checkout: |
            .github/workflows/sizeup/config.yml
          sparse-checkout-cone-mode: false

      - name: Run sizeup
        # https://github.com/lerebear/sizeup-action/blob/main/README.md#versioning
        uses: lerebear/sizeup-action@v0.8.3
        id: sizeup-action

        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

          configuration-file-path: .github/workflows/sizeup/config.yml
```

Thank you for your help !
