### ISSUE TITLE
Unable to evaluate PR

### ISSUE THREAD

**Issue by shamikct** [lerebear/sizeup-action#62]
Hello,

I have the following yml file:
```yaml
name: PR Size Up

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Estimate reviewability
    runs-on: ubuntu-latest

    steps:
      - name: Run sizeup
        uses: lerebear/sizeup-action@v0.8.8
        id: sizeup-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          git-diff-options: ""
          # Path to a YAML configuration file for this workflow that is stored
          # in this repository.
          #
          # This input defaults to "", which instructs the workflow to use the
          # built-in default configuration.
          configuration-file-path: ".github/workflows/sizeup/config.yml"

```

When i try to run it i get the following error:

```python
Run lerebear/sizeup-action@v0.8.8
  with:
    token: ***
    configuration-file-path: .github/workflows/sizeup/config.yml
Reading sizeup configuration from ".github/workflows/sizeup/config.yml"

Evaluating pull request codeandtheory/ctailml#158
Error: fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
